### ISSUE TITLE
Error when trying to start

### ISSUE THREAD

**Issue by volkerkarle** [davidbrochart/nbterm#46]
Hi, when trying to run nbterm (archlinux with python-ipykernel 5.5.3-1), I receive the following error message

`Traceback (most recent call last):
  File "/usr/bin/nbterm", line 33, in <module>
    sys.exit(load_entry_point('nbterm==0.0.11', 'console_scripts', 'nbterm')())
  File "/usr/bin/nbterm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/lib/python3.9/site-packages/nbterm/nbterm.py", line 6, in <module>
    import typer
  File "/usr/lib/python3.9/site-packages/typer/__init__.py", line 29, in <module>
    from .main import Typer as Typer
  File "/usr/lib/python3.9/site-packages/typer/main.py", line 11, in <module>
    from .completion import get_completion_inspect_parameters
  File "/usr/lib/python3.9/site-packages/typer/completion.py", line 10, in <module>
    import click._bashcomplete
ModuleNotFoundError: No module named 'click._bashcomplete'`

I figured that it is related to the module "python-click 8.0.1-1", which is properly installed. Ideas what I could try to get rid of this error? 

Best,

v.

**Comment by davidbrochart** [comment]
Yes, you need `click <8`. This will be fixed in next release, but `pip install click==7` should fix the issue for you (see #45).

**Comment by volkerkarle** [comment]
Thanks! That was fast!
