### ISSUE TITLE
Keyerror: 'language'

### ISSUE THREAD

**Issue by yashjakhotiya** [davidbrochart/nbterm#52]
```
 ➜  Downloads nbterm Yash\'s_copy_of_TextClassification_release.ipynb 
Traceback (most recent call last):
  File "/home/yash-jakhotiya/.local/bin/nbterm", line 8, in <module>
    sys.exit(cli())
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/nbterm/nbterm.py", line 85, in cli
    typer.run(main)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/typer/main.py", line 864, in run
    app()
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/typer/main.py", line 500, in wrapper
    return callback(**use_params)  # type: ignore
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/nbterm/nbterm.py", line 65, in main
    nb = Notebook(
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/nbterm/notebook.py", line 79, in __init__
    self.read_nb()
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/nbterm/format.py", line 16, in read_nb
    self.set_language()  # type: ignore
  File "/home/yash-jakhotiya/.local/lib/python3.8/site-packages/nbterm/notebook.py", line 91, in set_language
    self.language = self.json["metadata"]["kernelspec"]["language"]
KeyError: 'language'

```

**Comment by joshjetson** [comment]
I am experiencing the same issue.

**Comment by vinibosch** [comment]
same problem here
